name: Test
on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev
jobs:
    Test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: bun install
            - name: Lint & Test if desktop version compiles
              run: bun run test
            - name: Test if web version compiles
              run: bun run buildWeb
            - name: Test if plugin structure is valid
              run: bun run generatePluginJson
